### ISSUE TITLE
Licence ?

### ISSUE THREAD

**Issue by Rudloff** [Archi-Strasbourg/archi-mediawiki-skin#3]
@hiwelo @markjohnnightingale Je ne sais plus si on avait parlé de la question de la licence.
C'est a priori un pré-requis que tout le code du projet soit libre (ou au moins consultable).
Le reste du code d'Archi-Wiki est sous licence GPL mais on peut prendre une licence plus restrictive pour le skin si vous préférez (genre utilisation commerciale interdite).

**Comment by hiwelo** [comment]
Je n'ai pas d'opposition majeure à ce que le design soit dans une licence libre, à voir si @markjohnnightingale est d'accord pour que le code du skin le soit.

**Comment by markjohnnightingale** [comment]
Bonjour,

Pour le skin je n'ai pas de problèmes à le mettre sous GPL.

Mark



www.marknightingale.net
hello@marknightingale.net



hiwelo. wrote:

**Comment by Rudloff** [comment]
OK, si vous êtes d'accord tous les deux, je mets sous GPL comme ça c'est cohérent avec le reste 😺
